"""Second migration

Revision ID: 18576ce8d388
Revises: ef8bf7718ca7
Create Date: 2024-12-02 11:59:10.836918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18576ce8d388"
down_revision: Union[str, None] = "ef8bf7718ca7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["login"])
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
            "Token_validation",
            sa.Column("user", sa.String(length=30), nullable=False),
            sa.Column("jwt", sa.String(length=100), nullable=False),
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.ForeignKeyConstraint(
                ["user"],
                ["Users.login"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.add_column(
            "Tasks", sa.Column("owner", sa.String(length=30), nullable=False)
        )
        op.add_column(
            "Users", sa.Column("role", sa.String(length=30), nullable=False)
        )
        op.create_unique_constraint(None, "Users", ["login"])
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint(None, "Users", type_="unique")
        op.drop_column("Users", "role")
        op.drop_column("Tasks", "owner")
        op.drop_table("Token_validation")
    # ### end Alembic commands ###
